- name: Install packages necessary to build OBS
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ffmpeg
      - build-essential
      - checkinstall
      - cmake
      - git
      - libmbedtls-dev
      - libasound2-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavutil-dev
      - libcurl4-openssl-dev
      - libfdk-aac-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libjack-jackd2-dev
      - libjansson-dev
      - libluajit-5.1-dev
      - libpulse-dev
      - libqt5x11extras5-dev
      - libspeexdsp-dev
      - libswresample-dev
      - libswscale-dev
      - libudev-dev
      - libv4l-dev
      - libvlc-dev
      - libx11-dev
      - libx264-dev
      - libxcb-shm0-dev
      - libxcb-xinerama0-dev
      - libxcomposite-dev
      - libxinerama-dev
      - pkg-config
      - python3-dev
      - qtbase5-dev
      - libqt5svg5-dev
      - swig
      - libxcb-randr0-dev
      - libxcb-xfixes0-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libglfw3-dev
      - libgles2-mesa-dev
- name: Create build directory
  file:
    path: /home/src
    state: directory

- name: Check if CEF is installed
  stat:
    path: /home/src/cef_binary_4280_linux64
  register: cef_binary
- name: Install CEF
  shell: |
    set -e
    cd /home/src
    wget https://cdn-fastly.obsproject.com/downloads/cef_binary_4280_linux64.tar.bz2
    tar -xjf ./cef_binary_4280_linux64.tar.bz2
  when: not cef_binary.stat.exists

- name: Check if OBS source has been checked out
  stat:
    path: /home/src/obs-studio
  register: obs_source
- name: Check out OBS source
  shell: |
    set -e
    cd /home/src
    git clone --recursive --depth=1 --branch 26.1.2 https://github.com/obsproject/obs-studio.git
  when: not obs_source.stat.exists
- name: Check if OBS is installed
  stat:
    path: /usr/bin/obs
  register: obs
- name: Build OBS
  # https://github.com/obsproject/obs-studio/issues/2644#issuecomment-623168704
  shell: |
    set -e
    export QT_QPA_PLATFORMTHEME="qt5ct"
    cd /home/src/obs-studio
    mkdir build && cd build
    cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_4280_linux64" ..
    make -j4
    sudo checkinstall --default --pkgname=obs-studio --fstrans=no --backup=no --pkgversion="$(date +%Y%m%d)-git" --deldoc=yes
  when: not obs.stat.exists
