---
- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - chromium
      - curl
      - joe
      - libnginx-mod-rtmp
      - pavucontrol
      - task-mate-desktop
      - tmux
      - vlc
      - x11vnc
      - xvfb

- name: Install No Machine
  include: nomachine.yaml

- name: General configuration
  include: general.yaml

- name: Install OBS
  include: obs.yaml

- name: Configure Mumble
  include: mumble.yaml

- name: Configure NGINX
  include: nginx.yaml

- name: Configure Docker Compose
  include: compose.yaml
