- name: Check if OBS is installed
  command: dpkg-query -W obs-studio
  register: obs_check_deb
  failed_when: obs_check_deb.rc > 1
  changed_when: obs_check_deb.rc == 1

- name: Check for cached package
  stat:
    path: "/var/cache/dl/obs-studio_{{ obs_version }}-1_amd64.deb"
  register: obs_deb

- name: Install packages necessary to build OBS
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ffmpeg
      - build-essential
      - checkinstall
      - cmake
      - git
      - libmbedtls-dev
      - libasound2-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavutil-dev
      - libcurl4-openssl-dev
      - libfdk-aac-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libjack-jackd2-dev
      - libjansson-dev
      - libluajit-5.1-dev
      - libpulse-dev
      - libqt5x11extras5-dev
      - libspeexdsp-dev
      - libswresample-dev
      - libswscale-dev
      - libudev-dev
      - libv4l-dev
      - libvlc-dev
      - libx11-dev
      - libx264-dev
      - libxcb-shm0-dev
      - libxcb-xinerama0-dev
      - libxcomposite-dev
      - libxinerama-dev
      - pkg-config
      - python3-dev
      - qtbase5-dev
      - libqt5svg5-dev
      - swig
      - libxcb-randr0-dev
      - libxcb-xfixes0-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libglfw3-dev
      - libgles2-mesa-dev

- name: Install OBS from cached package
  apt: deb="/var/cache/dl/obs-studio_{{ obs_version }}-1_amd64.deb"
  when: obs_check_deb.rc == 1 and obs_deb.stat.exists

- name: Install OBS from source
  include: obs-build.yaml
  when: "obs_check_deb.rc == 1 and not obs_deb.stat.exists"
